title: Web Chef, Customary Coder.
email: mlrcbsousa@gmail.com
handle: mlrcbsousa
description: >-
  Award winning Maths student turned Economist turned
  Chef turned Software Engineer. Always learning. I enjoy writing clean clear code
  and building things people want to use.
baseurl: ""
url: "https://www.mlrcbsousa.com"
google_analytics: UA-129352462-1

# Layout
header_pages:
  - resume.html
  - blog/index.html
  - projects.html
skills_column_size: 12

# Pagination
paginate: 5
paginate_path: "/blog/:num/"

# Formatting
date_format: "%b %-d, %Y"

# Author
author:
  name: Manuel Sousa
  email: mlrcbsousa@gmail.com

# Comments
disqus:
  shortname: mlrcbsousa

# Social
social:
  github:  mlrcbsousa
  linkedin: mlrcbsousa
  twitter: mlrcbsousa

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      math: true
      layout: post
      permalink: /:title/
      comments: true
  - scope:
      path: "images"
    values:
      image: true

# Math and Markdown (includes overrides by GH pages)
highlighter: rouge
markdown: kramdown
kramdown:
  template: ""
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: shell
#  math_engine_opts:

exclude:
  - README.md
  - resume/README.md
  - images/nice-blues.png
  - Gemfile
  - Gemfile.lock
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
