title: Web Chef, Customary Coder.
email: mlrcbsousa@gmail.com
handle: mlrcbsousa
description: >-
  Award winning Maths student turned Economist turned
  Chef turned Software Engineer. Always learning. I enjoy writing clean clear code
  and building things people want to use.
baseurl: ""
url: "https://www.mlrcbsousa.com"
google_analytics: UA-129352462-1

# Layout
header_pages:
  - resume.html
  - blog/index.html
  - projects.markdown
paginate: 5
paginate_path: "/blog/:num/"

skills_column_size: 12

# Author
author:
  name: Manuel Sousa
  email: mlrcbsousa@gmail.com

# Comments
disqus:
  shortname: mlrcbsousa

# Social
social:
  github:  mlrcbsousa
  linkedin: mlrcbsousa
  twitter: mlrcbsousa

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /:title/
      comments: true
  - scope:
      path: "images"
    values:
      image: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
